{
 "title": "Player Dashboard",
 "time": { "from": "now-6h", "to": "now-1m" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "username",
    "query": "SHOW TAG VALUES WITH KEY = \"user\""
   },
   {
    "name": "itemset",
    "query": "SHOW TAG VALUES WITH KEY = \"inventory\""
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Combat Level",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs_self",
     "select": [
      [
       { "params": [ "combat" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Total XP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs_skill",
     "select": [
      [
       { "params": [ "xp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "skill", "operator": "=", "value": "OVERALL" }
     ]
    }
   ]
  },
  {
   "title": "Total Level",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs_skill",
     "select": [
      [
       { "params": [ "realLevel" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "skill", "operator": "=", "value": "OVERALL" }
     ]
    }
   ]
  },
  {
   "title": "$itemset Value (GE)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs_inventory",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "GE" },
      { "condition": "AND", "key": "inventory", "operator": "=~", "value": "/^$itemset$/" }
     ]
    }
   ]
  },
  {
   "title": "$itemset gain (GE)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "diff",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "rs_inventory",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "GE" },
      { "condition": "AND", "key": "inventory", "operator": "=~", "value": "/^$itemset$/" }
     ]
    }
   ]
  },
  {
   "title": "XP Gain",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "diff",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs_skill",
     "select": [
      [
       { "params": [ "xp" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "skill", "operator": "=", "value": "OVERALL" }
     ]
    }
   ]
  },
  { "title": "Skills", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Experience",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_skill",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "skill" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rs_skill",
     "query": "SELECT max(*) FROM \"rs_skill_xp\" WHERE (\"username\" =~ /^$username$/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "xp" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "XP Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "xp/hr" }
   ],
   "targets": [
    {
     "alias": "$tag_skill",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "skill" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rs_skill",
     "query": "SELECT derivative(max(*), 1h) AS \" \" FROM \"rs_skill_xp\" WHERE (\"username\" =~ /^$username$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "xp" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Levels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_skill",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "skill" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rs_skill",
     "query": "SELECT max(*) FROM \"rs_skill_xp\" WHERE (\"username\" =~ /^$username$/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "virtualLevel" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "skill", "operator": "!=", "value": "OVERALL" }
     ]
    }
   ]
  },
  {
   "title": "Items",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "$itemset Value (GE)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "gp" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "10m" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "rs_inventory",
       "select": [
        [
         { "params": [ "*" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ " " ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "user", "operator": "=~", "value": "/^$username$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "GE" },
        { "condition": "AND", "key": "inventory", "operator": "=~", "value": "/^$itemset$/" }
       ]
      }
     ]
    },
    {
     "title": "$itemset Quantity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "10m" ], "type": "time" },
        { "params": [ "type" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "rs_inventory",
       "select": [
        [
         { "params": [ "*" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ " " ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "user", "operator": "=~", "value": "/^$username$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "COUNT" },
        { "condition": "AND", "key": "inventory", "operator": "=~", "value": "/^$itemset$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Daily", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Daily XP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_skill",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "skill" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rs_skill",
     "query": "SELECT derivative(max(*), 1h) AS \" \" FROM \"rs_skill_xp\" WHERE (\"username\" =~ /^$username$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "xp" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Daily Profits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_inventory",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "inventory" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rs_inventory",
     "query": "SELECT derivative(max(*), 1h) AS \" \" FROM \"rs_skill_xp\" WHERE (\"username\" =~ /^$username$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "GE" }
     ]
    }
   ]
  },
  {
   "title": "Daily Bosses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_boss",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "boss" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rs_killcount",
     "query": "SELECT derivative(max(*), 1h) AS \" \" FROM \"rs_skill_xp\" WHERE (\"username\" =~ /^$username$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "kc" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  { "title": "Bosses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Kill Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_boss]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "boss" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rs_killcount",
     "select": [
      [
       { "params": [ "kc" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Best Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "[[tag_boss]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "boss" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rs_killcount",
     "select": [
      [
       { "params": [ "pb" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Activity",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "alias": "skill",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs_activity",
     "query": "SELECT last(\"skill\") FROM \"rs_activity\" WHERE (\"user\" =~ /^$username$/) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "skill" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "location",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rs_activity",
     "select": [
      [
       { "params": [ "location" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  }
 ]
}